# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions


from . import stream_types, types
from .runtime import DoNotUseDirectlyCallManager, BamlCallOptions

class LlmResponseParser:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def ArchitectFeature(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.TechPlan:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="ArchitectFeature", llm_response=llm_response, mode="request")
        return typing.cast(types.TechPlan, __result__)

    def BuildFeature(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> typing.Union["types.BuilderToolCall", "types.BuilderFinal"]:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="BuildFeature", llm_response=llm_response, mode="request")
        return typing.cast(typing.Union["types.BuilderToolCall", "types.BuilderFinal"], __result__)

    def ClarifySpecs(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.ClarifierOutput:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="ClarifySpecs", llm_response=llm_response, mode="request")
        return typing.cast(types.ClarifierOutput, __result__)

    def MapAndIndex(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> typing.Union["types.MapperToolCall", "types.MapperFinal"]:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="MapAndIndex", llm_response=llm_response, mode="request")
        return typing.cast(typing.Union["types.MapperToolCall", "types.MapperFinal"], __result__)

    def PlanFeatures(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.FeaturePlan:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="PlanFeatures", llm_response=llm_response, mode="request")
        return typing.cast(types.FeaturePlan, __result__)

    def PreflightMap(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.MapperReport:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="PreflightMap", llm_response=llm_response, mode="request")
        return typing.cast(types.MapperReport, __result__)

    def RefineApproaches(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.Decision:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="RefineApproaches", llm_response=llm_response, mode="request")
        return typing.cast(types.Decision, __result__)

    def ResearchFeature(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.ResearchFindings:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="ResearchFeature", llm_response=llm_response, mode="request")
        return typing.cast(types.ResearchFindings, __result__)

    def VerifyBuild(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> typing.Union["types.VerifierToolCall", "types.VerifierFinal"]:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="VerifyBuild", llm_response=llm_response, mode="request")
        return typing.cast(typing.Union["types.VerifierToolCall", "types.VerifierFinal"], __result__)

    

class LlmStreamParser:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def ArchitectFeature(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.TechPlan:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="ArchitectFeature", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.TechPlan, __result__)

    def BuildFeature(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> typing.Union["stream_types.BuilderToolCall", "stream_types.BuilderFinal"]:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="BuildFeature", llm_response=llm_response, mode="stream")
        return typing.cast(typing.Union["stream_types.BuilderToolCall", "stream_types.BuilderFinal"], __result__)

    def ClarifySpecs(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.ClarifierOutput:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="ClarifySpecs", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.ClarifierOutput, __result__)

    def MapAndIndex(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> typing.Union["stream_types.MapperToolCall", "stream_types.MapperFinal"]:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="MapAndIndex", llm_response=llm_response, mode="stream")
        return typing.cast(typing.Union["stream_types.MapperToolCall", "stream_types.MapperFinal"], __result__)

    def PlanFeatures(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.FeaturePlan:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="PlanFeatures", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.FeaturePlan, __result__)

    def PreflightMap(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.MapperReport:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="PreflightMap", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.MapperReport, __result__)

    def RefineApproaches(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.Decision:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="RefineApproaches", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.Decision, __result__)

    def ResearchFeature(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.ResearchFindings:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="ResearchFeature", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.ResearchFindings, __result__)

    def VerifyBuild(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> typing.Union["stream_types.VerifierToolCall", "stream_types.VerifierFinal"]:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="VerifyBuild", llm_response=llm_response, mode="stream")
        return typing.cast(typing.Union["stream_types.VerifierToolCall", "stream_types.VerifierFinal"], __result__)

    