# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
from pydantic import BaseModel, ConfigDict, Field

import baml_py

from . import types

StreamStateValueT = typing.TypeVar('StreamStateValueT')
class StreamState(BaseModel, typing.Generic[StreamStateValueT]):
    value: StreamStateValueT
    state: typing_extensions.Literal["Pending", "Incomplete", "Complete"]
# #########################################################################
# Generated classes (23)
# #########################################################################

class Approach(BaseModel):
    name: typing.Optional[str] = Field(default=None, description='2-4 word approach name')
    description: typing.Optional[str] = Field(default=None, description='3-5 sentence explanation')
    simplicity: typing.Optional[int] = Field(default=None, description='1-5')
    completeness: typing.Optional[int] = Field(default=None, description='1-5')
    risk: typing.Optional[int] = Field(default=None, description='1-5, 5=lowest risk')
    fit: typing.Optional[int] = Field(default=None, description='1-5')

class BuilderFinal(BaseModel):
    report: typing.Optional["BuilderReport"] = None

class BuilderQuestionsEntry(BaseModel):
    slug: typing.Optional[str] = None
    timestamp: typing.Optional[str] = Field(default=None, description='ISO 8601')
    questions: typing.List[str] = Field(description='Markdown list items with - [ ] prefix')

class BuilderReport(BaseModel):
    commit_made: typing.Optional[bool] = None
    open_questions: typing.List[str] = Field(description='Ambiguities that surfaced during implementation')
    deviations: typing.List[str] = Field(description='What changed from the plan and why')

class BuilderToolCall(BaseModel):
    tool_name: typing.Optional[str] = Field(default=None, description='vault_read | vault_write | run_shell_command')
    args: typing.Dict[str, str]

class ClarifierOutput(BaseModel):
    has_ambiguities: typing.Optional[bool] = None
    questions: typing.List["ClarifierQuestion"] = Field(description='Up to 10 blocking questions')

class ClarifierQuestion(BaseModel):
    feature: typing.Optional[str] = Field(default=None, description='Feature or file the question targets')
    question: typing.Optional[str] = Field(default=None, description='Single-sentence question')
    context: typing.Optional[str] = Field(default=None, description='Why this matters — 1-2 sentences')

class CriterionMap(BaseModel):
    criterion_number: typing.Optional[int] = None
    verification: typing.Optional[str] = Field(default=None, description='Concrete test or verification step')

class Decision(BaseModel):
    approaches: typing.List["Approach"] = Field(description='Exactly 3 distinct approaches')
    chosen: typing.Optional[int] = Field(default=None, description='1, 2, or 3 — highest total score, prefer simpler on tie')
    rationale: typing.Optional[str] = Field(default=None, description='Why this approach was chosen')

class Failure(BaseModel):
    check_type: typing.Optional[str] = Field(default=None, description='typecheck | lint | test')
    command: typing.Optional[str] = Field(default=None, description='The command that was run')
    error_message: typing.Optional[str] = Field(default=None, description='Trimmed error output')
    likely_cause: typing.Optional[str] = Field(default=None, description='One-sentence diagnosis')
    criterion_impact: typing.Optional[str] = Field(default=None, description='Which criterion this affects, or \'No criterion mapped\'')

class Feature(BaseModel):
    slug: typing.Optional[str] = Field(default=None, description='kebab-case, alphanumerics and hyphens only, max 40 chars')
    description: typing.Optional[str] = Field(default=None, description='One-line feature summary')
    acceptance_criteria: typing.List[str] = Field(description='2-8 user-observable invariants')

class FeaturePlan(BaseModel):
    features: typing.List["Feature"]

class FileSpec(BaseModel):
    path: typing.Optional[str] = None
    purpose: typing.Optional[str] = None

class MapperFinal(BaseModel):
    report: typing.Optional["MapperReport"] = None

class MapperReport(BaseModel):
    entities_updated: typing.List[str]
    log_entry: typing.Optional[str] = Field(default=None, description='One-sentence summary for log.md')
    deviations_summary: typing.Optional[str] = Field(default=None, description='Deviations section text for TECH.md, or \'Implementation matched plan — no deviations.\'')

class MapperToolCall(BaseModel):
    tool_name: typing.Optional[str] = Field(default=None, description='vault_read | vault_write | run_shell_command')
    args: typing.Dict[str, str]

class ResearchFinding(BaseModel):
    title: typing.Optional[str] = None
    insight: typing.Optional[str] = Field(default=None, description='2-4 sentence key insight')
    relevance: typing.Optional[str] = Field(default=None, description='One-sentence relevance to this feature')
    confidence: typing.Optional[str] = Field(default=None, description='High | Medium | Low')
    source_url: typing.Optional[str] = Field(default=None, description='If web search was used')

class ResearchFindings(BaseModel):
    findings: typing.List["ResearchFinding"]
    recommendations: typing.List[str]

class TechPlan(BaseModel):
    context: typing.Optional[str] = Field(default=None, description='What\'s being built and current system context')
    files_to_create: typing.List["FileSpec"]
    files_to_modify: typing.List["FileSpec"]
    interfaces: typing.Optional[str] = Field(default=None, description='Function signatures / API shapes / type definitions')
    edge_cases: typing.List[str]
    criteria_mapping: typing.List["CriterionMap"]

class ToolCall(BaseModel):
    tool_name: typing.Optional[str] = Field(default=None, description='vault_read | vault_write | run_shell_command | web_search')
    args: typing.Dict[str, str]

class VerifierFinal(BaseModel):
    report: typing.Optional["VerifierReport"] = None

class VerifierReport(BaseModel):
    status: typing.Optional[str] = Field(default=None, description='PASSED or FAILED')
    failures: typing.List["Failure"]
    fix_hints: typing.List[str] = Field(description='Concrete file-level suggestions')

class VerifierToolCall(BaseModel):
    tool_name: typing.Optional[str] = Field(default=None, description='vault_read | run_shell_command')
    args: typing.Dict[str, str]

# #########################################################################
# Generated type aliases (3)
# #########################################################################


BuilderStep: typing_extensions.TypeAlias = typing.Optional[typing.Union["BuilderToolCall", "BuilderFinal"]]


MapperStep: typing_extensions.TypeAlias = typing.Optional[typing.Union["MapperToolCall", "MapperFinal"]]


VerifierStep: typing_extensions.TypeAlias = typing.Optional[typing.Union["VerifierToolCall", "VerifierFinal"]]
