# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
import baml_py

from . import stream_types, types, type_builder
from .parser import LlmResponseParser, LlmStreamParser
from .runtime import DoNotUseDirectlyCallManager, BamlCallOptions
from .globals import DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_RUNTIME as __runtime__

class BamlSyncClient:
    __options: DoNotUseDirectlyCallManager
    __stream_client: "BamlStreamClient"
    __http_request: "BamlHttpRequestClient"
    __http_stream_request: "BamlHttpStreamRequestClient"
    __llm_response_parser: LlmResponseParser
    __llm_stream_parser: LlmStreamParser

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options
        self.__stream_client = BamlStreamClient(options)
        self.__http_request = BamlHttpRequestClient(options)
        self.__http_stream_request = BamlHttpStreamRequestClient(options)
        self.__llm_response_parser = LlmResponseParser(options)
        self.__llm_stream_parser = LlmStreamParser(options)

    def __getstate__(self):
        # Return state needed for pickling
        return {"options": self.__options}

    def __setstate__(self, state):
        # Restore state from pickling
        self.__options = state["options"]
        self.__stream_client = BamlStreamClient(self.__options)
        self.__http_request = BamlHttpRequestClient(self.__options)
        self.__http_stream_request = BamlHttpStreamRequestClient(self.__options)
        self.__llm_response_parser = LlmResponseParser(self.__options)
        self.__llm_stream_parser = LlmStreamParser(self.__options)

    def with_options(self,
        tb: typing.Optional[type_builder.TypeBuilder] = None,
        client_registry: typing.Optional[baml_py.baml_py.ClientRegistry] = None,
        client: typing.Optional[str] = None,
        collector: typing.Optional[typing.Union[baml_py.baml_py.Collector, typing.List[baml_py.baml_py.Collector]]] = None,
        env: typing.Optional[typing.Dict[str, typing.Optional[str]]] = None,
        tags: typing.Optional[typing.Dict[str, str]] = None,
        on_tick: typing.Optional[typing.Callable[[str, baml_py.baml_py.FunctionLog], None]] = None,
    ) -> "BamlSyncClient":
        options: BamlCallOptions = {}
        if tb is not None:
            options["tb"] = tb
        if client_registry is not None:
            options["client_registry"] = client_registry
        if client is not None:
            options["client"] = client
        if collector is not None:
            options["collector"] = collector
        if env is not None:
            options["env"] = env
        if tags is not None:
            options["tags"] = tags
        if on_tick is not None:
            options["on_tick"] = on_tick
        return BamlSyncClient(self.__options.merge_options(options))

    @property
    def stream(self):
      return self.__stream_client

    @property
    def request(self):
      return self.__http_request

    @property
    def stream_request(self):
      return self.__http_stream_request

    @property
    def parse(self):
      return self.__llm_response_parser

    @property
    def parse_stream(self):
      return self.__llm_stream_parser

    def ArchitectFeature(self, feature_name: str,slug: str,vault_structure: str,vault_entrypoints: str,acceptance_criteria: str,decision_text: typing.Optional[str] = None,research_findings: typing.Optional[str] = None,
        baml_options: BamlCallOptions = {},
    ) -> types.TechPlan:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            __stream__ = self.stream.ArchitectFeature(feature_name=feature_name,slug=slug,vault_structure=vault_structure,vault_entrypoints=vault_entrypoints,acceptance_criteria=acceptance_criteria,decision_text=decision_text,research_findings=research_findings,
                baml_options=baml_options)
            return __stream__.get_final_response()
        else:
            # Original non-streaming code
            __result__ = self.__options.merge_options(baml_options).call_function_sync(function_name="ArchitectFeature", args={
                "feature_name": feature_name,"slug": slug,"vault_structure": vault_structure,"vault_entrypoints": vault_entrypoints,"acceptance_criteria": acceptance_criteria,"decision_text": decision_text,"research_findings": research_findings,
            })
            return typing.cast(types.TechPlan, __result__.cast_to(types, types, stream_types, False, __runtime__))
    def BuildFeature(self, tech_plan: str,decision_text: typing.Optional[str],slug: str,feature_description: str,history: str,
        baml_options: BamlCallOptions = {},
    ) -> typing.Union["types.BuilderToolCall", "types.BuilderFinal"]:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            __stream__ = self.stream.BuildFeature(tech_plan=tech_plan,decision_text=decision_text,slug=slug,feature_description=feature_description,history=history,
                baml_options=baml_options)
            return __stream__.get_final_response()
        else:
            # Original non-streaming code
            __result__ = self.__options.merge_options(baml_options).call_function_sync(function_name="BuildFeature", args={
                "tech_plan": tech_plan,"decision_text": decision_text,"slug": slug,"feature_description": feature_description,"history": history,
            })
            return typing.cast(typing.Union["types.BuilderToolCall", "types.BuilderFinal"], __result__.cast_to(types, types, stream_types, False, __runtime__))
    def ClarifySpecs(self, specs_content: str,
        baml_options: BamlCallOptions = {},
    ) -> types.ClarifierOutput:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            __stream__ = self.stream.ClarifySpecs(specs_content=specs_content,
                baml_options=baml_options)
            return __stream__.get_final_response()
        else:
            # Original non-streaming code
            __result__ = self.__options.merge_options(baml_options).call_function_sync(function_name="ClarifySpecs", args={
                "specs_content": specs_content,
            })
            return typing.cast(types.ClarifierOutput, __result__.cast_to(types, types, stream_types, False, __runtime__))
    def MapAndIndex(self, git_diff: str,slug: str,feature_description: str,plan_text: str,tech_plan: str,index_text: str,history: str,
        baml_options: BamlCallOptions = {},
    ) -> typing.Union["types.MapperToolCall", "types.MapperFinal"]:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            __stream__ = self.stream.MapAndIndex(git_diff=git_diff,slug=slug,feature_description=feature_description,plan_text=plan_text,tech_plan=tech_plan,index_text=index_text,history=history,
                baml_options=baml_options)
            return __stream__.get_final_response()
        else:
            # Original non-streaming code
            __result__ = self.__options.merge_options(baml_options).call_function_sync(function_name="MapAndIndex", args={
                "git_diff": git_diff,"slug": slug,"feature_description": feature_description,"plan_text": plan_text,"tech_plan": tech_plan,"index_text": index_text,"history": history,
            })
            return typing.cast(typing.Union["types.MapperToolCall", "types.MapperFinal"], __result__.cast_to(types, types, stream_types, False, __runtime__))
    def PlanFeatures(self, specs_content: str,clarifications: str,existing_plan: str,
        baml_options: BamlCallOptions = {},
    ) -> types.FeaturePlan:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            __stream__ = self.stream.PlanFeatures(specs_content=specs_content,clarifications=clarifications,existing_plan=existing_plan,
                baml_options=baml_options)
            return __stream__.get_final_response()
        else:
            # Original non-streaming code
            __result__ = self.__options.merge_options(baml_options).call_function_sync(function_name="PlanFeatures", args={
                "specs_content": specs_content,"clarifications": clarifications,"existing_plan": existing_plan,
            })
            return typing.cast(types.FeaturePlan, __result__.cast_to(types, types, stream_types, False, __runtime__))
    def PreflightMap(self, file_listing: str,manifest_files: str,history: str,
        baml_options: BamlCallOptions = {},
    ) -> types.MapperReport:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            __stream__ = self.stream.PreflightMap(file_listing=file_listing,manifest_files=manifest_files,history=history,
                baml_options=baml_options)
            return __stream__.get_final_response()
        else:
            # Original non-streaming code
            __result__ = self.__options.merge_options(baml_options).call_function_sync(function_name="PreflightMap", args={
                "file_listing": file_listing,"manifest_files": manifest_files,"history": history,
            })
            return typing.cast(types.MapperReport, __result__.cast_to(types, types, stream_types, False, __runtime__))
    def RefineApproaches(self, feature_name: str,slug: str,vault_overview: str,vault_structure: str,vault_deps: str,acceptance_criteria: str,research_findings: typing.Optional[str] = None,
        baml_options: BamlCallOptions = {},
    ) -> types.Decision:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            __stream__ = self.stream.RefineApproaches(feature_name=feature_name,slug=slug,vault_overview=vault_overview,vault_structure=vault_structure,vault_deps=vault_deps,acceptance_criteria=acceptance_criteria,research_findings=research_findings,
                baml_options=baml_options)
            return __stream__.get_final_response()
        else:
            # Original non-streaming code
            __result__ = self.__options.merge_options(baml_options).call_function_sync(function_name="RefineApproaches", args={
                "feature_name": feature_name,"slug": slug,"vault_overview": vault_overview,"vault_structure": vault_structure,"vault_deps": vault_deps,"acceptance_criteria": acceptance_criteria,"research_findings": research_findings,
            })
            return typing.cast(types.Decision, __result__.cast_to(types, types, stream_types, False, __runtime__))
    def ResearchFeature(self, feature_name: str,slug: str,research_type: str,sub_prompt: typing.Optional[str],vault_overview: str,vault_structure: str,
        baml_options: BamlCallOptions = {},
    ) -> types.ResearchFindings:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            __stream__ = self.stream.ResearchFeature(feature_name=feature_name,slug=slug,research_type=research_type,sub_prompt=sub_prompt,vault_overview=vault_overview,vault_structure=vault_structure,
                baml_options=baml_options)
            return __stream__.get_final_response()
        else:
            # Original non-streaming code
            __result__ = self.__options.merge_options(baml_options).call_function_sync(function_name="ResearchFeature", args={
                "feature_name": feature_name,"slug": slug,"research_type": research_type,"sub_prompt": sub_prompt,"vault_overview": vault_overview,"vault_structure": vault_structure,
            })
            return typing.cast(types.ResearchFindings, __result__.cast_to(types, types, stream_types, False, __runtime__))
    def VerifyBuild(self, tech_plan: str,slug: str,history: str,
        baml_options: BamlCallOptions = {},
    ) -> typing.Union["types.VerifierToolCall", "types.VerifierFinal"]:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            __stream__ = self.stream.VerifyBuild(tech_plan=tech_plan,slug=slug,history=history,
                baml_options=baml_options)
            return __stream__.get_final_response()
        else:
            # Original non-streaming code
            __result__ = self.__options.merge_options(baml_options).call_function_sync(function_name="VerifyBuild", args={
                "tech_plan": tech_plan,"slug": slug,"history": history,
            })
            return typing.cast(typing.Union["types.VerifierToolCall", "types.VerifierFinal"], __result__.cast_to(types, types, stream_types, False, __runtime__))
    


class BamlStreamClient:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def ArchitectFeature(self, feature_name: str,slug: str,vault_structure: str,vault_entrypoints: str,acceptance_criteria: str,decision_text: typing.Optional[str] = None,research_findings: typing.Optional[str] = None,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[stream_types.TechPlan, types.TechPlan]:
        __ctx__, __result__ = self.__options.merge_options(baml_options).create_sync_stream(function_name="ArchitectFeature", args={
            "feature_name": feature_name,"slug": slug,"vault_structure": vault_structure,"vault_entrypoints": vault_entrypoints,"acceptance_criteria": acceptance_criteria,"decision_text": decision_text,"research_findings": research_findings,
        })
        return baml_py.BamlSyncStream[stream_types.TechPlan, types.TechPlan](
          __result__,
          lambda x: typing.cast(stream_types.TechPlan, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.TechPlan, x.cast_to(types, types, stream_types, False, __runtime__)),
          __ctx__,
        )
    def BuildFeature(self, tech_plan: str,decision_text: typing.Optional[str],slug: str,feature_description: str,history: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[typing.Union["stream_types.BuilderToolCall", "stream_types.BuilderFinal"], typing.Union["types.BuilderToolCall", "types.BuilderFinal"]]:
        __ctx__, __result__ = self.__options.merge_options(baml_options).create_sync_stream(function_name="BuildFeature", args={
            "tech_plan": tech_plan,"decision_text": decision_text,"slug": slug,"feature_description": feature_description,"history": history,
        })
        return baml_py.BamlSyncStream[typing.Union["stream_types.BuilderToolCall", "stream_types.BuilderFinal"], typing.Union["types.BuilderToolCall", "types.BuilderFinal"]](
          __result__,
          lambda x: typing.cast(typing.Union["stream_types.BuilderToolCall", "stream_types.BuilderFinal"], x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(typing.Union["types.BuilderToolCall", "types.BuilderFinal"], x.cast_to(types, types, stream_types, False, __runtime__)),
          __ctx__,
        )
    def ClarifySpecs(self, specs_content: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[stream_types.ClarifierOutput, types.ClarifierOutput]:
        __ctx__, __result__ = self.__options.merge_options(baml_options).create_sync_stream(function_name="ClarifySpecs", args={
            "specs_content": specs_content,
        })
        return baml_py.BamlSyncStream[stream_types.ClarifierOutput, types.ClarifierOutput](
          __result__,
          lambda x: typing.cast(stream_types.ClarifierOutput, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.ClarifierOutput, x.cast_to(types, types, stream_types, False, __runtime__)),
          __ctx__,
        )
    def MapAndIndex(self, git_diff: str,slug: str,feature_description: str,plan_text: str,tech_plan: str,index_text: str,history: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[typing.Union["stream_types.MapperToolCall", "stream_types.MapperFinal"], typing.Union["types.MapperToolCall", "types.MapperFinal"]]:
        __ctx__, __result__ = self.__options.merge_options(baml_options).create_sync_stream(function_name="MapAndIndex", args={
            "git_diff": git_diff,"slug": slug,"feature_description": feature_description,"plan_text": plan_text,"tech_plan": tech_plan,"index_text": index_text,"history": history,
        })
        return baml_py.BamlSyncStream[typing.Union["stream_types.MapperToolCall", "stream_types.MapperFinal"], typing.Union["types.MapperToolCall", "types.MapperFinal"]](
          __result__,
          lambda x: typing.cast(typing.Union["stream_types.MapperToolCall", "stream_types.MapperFinal"], x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(typing.Union["types.MapperToolCall", "types.MapperFinal"], x.cast_to(types, types, stream_types, False, __runtime__)),
          __ctx__,
        )
    def PlanFeatures(self, specs_content: str,clarifications: str,existing_plan: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[stream_types.FeaturePlan, types.FeaturePlan]:
        __ctx__, __result__ = self.__options.merge_options(baml_options).create_sync_stream(function_name="PlanFeatures", args={
            "specs_content": specs_content,"clarifications": clarifications,"existing_plan": existing_plan,
        })
        return baml_py.BamlSyncStream[stream_types.FeaturePlan, types.FeaturePlan](
          __result__,
          lambda x: typing.cast(stream_types.FeaturePlan, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.FeaturePlan, x.cast_to(types, types, stream_types, False, __runtime__)),
          __ctx__,
        )
    def PreflightMap(self, file_listing: str,manifest_files: str,history: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[stream_types.MapperReport, types.MapperReport]:
        __ctx__, __result__ = self.__options.merge_options(baml_options).create_sync_stream(function_name="PreflightMap", args={
            "file_listing": file_listing,"manifest_files": manifest_files,"history": history,
        })
        return baml_py.BamlSyncStream[stream_types.MapperReport, types.MapperReport](
          __result__,
          lambda x: typing.cast(stream_types.MapperReport, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.MapperReport, x.cast_to(types, types, stream_types, False, __runtime__)),
          __ctx__,
        )
    def RefineApproaches(self, feature_name: str,slug: str,vault_overview: str,vault_structure: str,vault_deps: str,acceptance_criteria: str,research_findings: typing.Optional[str] = None,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[stream_types.Decision, types.Decision]:
        __ctx__, __result__ = self.__options.merge_options(baml_options).create_sync_stream(function_name="RefineApproaches", args={
            "feature_name": feature_name,"slug": slug,"vault_overview": vault_overview,"vault_structure": vault_structure,"vault_deps": vault_deps,"acceptance_criteria": acceptance_criteria,"research_findings": research_findings,
        })
        return baml_py.BamlSyncStream[stream_types.Decision, types.Decision](
          __result__,
          lambda x: typing.cast(stream_types.Decision, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.Decision, x.cast_to(types, types, stream_types, False, __runtime__)),
          __ctx__,
        )
    def ResearchFeature(self, feature_name: str,slug: str,research_type: str,sub_prompt: typing.Optional[str],vault_overview: str,vault_structure: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[stream_types.ResearchFindings, types.ResearchFindings]:
        __ctx__, __result__ = self.__options.merge_options(baml_options).create_sync_stream(function_name="ResearchFeature", args={
            "feature_name": feature_name,"slug": slug,"research_type": research_type,"sub_prompt": sub_prompt,"vault_overview": vault_overview,"vault_structure": vault_structure,
        })
        return baml_py.BamlSyncStream[stream_types.ResearchFindings, types.ResearchFindings](
          __result__,
          lambda x: typing.cast(stream_types.ResearchFindings, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.ResearchFindings, x.cast_to(types, types, stream_types, False, __runtime__)),
          __ctx__,
        )
    def VerifyBuild(self, tech_plan: str,slug: str,history: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[typing.Union["stream_types.VerifierToolCall", "stream_types.VerifierFinal"], typing.Union["types.VerifierToolCall", "types.VerifierFinal"]]:
        __ctx__, __result__ = self.__options.merge_options(baml_options).create_sync_stream(function_name="VerifyBuild", args={
            "tech_plan": tech_plan,"slug": slug,"history": history,
        })
        return baml_py.BamlSyncStream[typing.Union["stream_types.VerifierToolCall", "stream_types.VerifierFinal"], typing.Union["types.VerifierToolCall", "types.VerifierFinal"]](
          __result__,
          lambda x: typing.cast(typing.Union["stream_types.VerifierToolCall", "stream_types.VerifierFinal"], x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(typing.Union["types.VerifierToolCall", "types.VerifierFinal"], x.cast_to(types, types, stream_types, False, __runtime__)),
          __ctx__,
        )
    

class BamlHttpRequestClient:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def ArchitectFeature(self, feature_name: str,slug: str,vault_structure: str,vault_entrypoints: str,acceptance_criteria: str,decision_text: typing.Optional[str] = None,research_findings: typing.Optional[str] = None,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = self.__options.merge_options(baml_options).create_http_request_sync(function_name="ArchitectFeature", args={
            "feature_name": feature_name,"slug": slug,"vault_structure": vault_structure,"vault_entrypoints": vault_entrypoints,"acceptance_criteria": acceptance_criteria,"decision_text": decision_text,"research_findings": research_findings,
        }, mode="request")
        return __result__
    def BuildFeature(self, tech_plan: str,decision_text: typing.Optional[str],slug: str,feature_description: str,history: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = self.__options.merge_options(baml_options).create_http_request_sync(function_name="BuildFeature", args={
            "tech_plan": tech_plan,"decision_text": decision_text,"slug": slug,"feature_description": feature_description,"history": history,
        }, mode="request")
        return __result__
    def ClarifySpecs(self, specs_content: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = self.__options.merge_options(baml_options).create_http_request_sync(function_name="ClarifySpecs", args={
            "specs_content": specs_content,
        }, mode="request")
        return __result__
    def MapAndIndex(self, git_diff: str,slug: str,feature_description: str,plan_text: str,tech_plan: str,index_text: str,history: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = self.__options.merge_options(baml_options).create_http_request_sync(function_name="MapAndIndex", args={
            "git_diff": git_diff,"slug": slug,"feature_description": feature_description,"plan_text": plan_text,"tech_plan": tech_plan,"index_text": index_text,"history": history,
        }, mode="request")
        return __result__
    def PlanFeatures(self, specs_content: str,clarifications: str,existing_plan: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = self.__options.merge_options(baml_options).create_http_request_sync(function_name="PlanFeatures", args={
            "specs_content": specs_content,"clarifications": clarifications,"existing_plan": existing_plan,
        }, mode="request")
        return __result__
    def PreflightMap(self, file_listing: str,manifest_files: str,history: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = self.__options.merge_options(baml_options).create_http_request_sync(function_name="PreflightMap", args={
            "file_listing": file_listing,"manifest_files": manifest_files,"history": history,
        }, mode="request")
        return __result__
    def RefineApproaches(self, feature_name: str,slug: str,vault_overview: str,vault_structure: str,vault_deps: str,acceptance_criteria: str,research_findings: typing.Optional[str] = None,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = self.__options.merge_options(baml_options).create_http_request_sync(function_name="RefineApproaches", args={
            "feature_name": feature_name,"slug": slug,"vault_overview": vault_overview,"vault_structure": vault_structure,"vault_deps": vault_deps,"acceptance_criteria": acceptance_criteria,"research_findings": research_findings,
        }, mode="request")
        return __result__
    def ResearchFeature(self, feature_name: str,slug: str,research_type: str,sub_prompt: typing.Optional[str],vault_overview: str,vault_structure: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = self.__options.merge_options(baml_options).create_http_request_sync(function_name="ResearchFeature", args={
            "feature_name": feature_name,"slug": slug,"research_type": research_type,"sub_prompt": sub_prompt,"vault_overview": vault_overview,"vault_structure": vault_structure,
        }, mode="request")
        return __result__
    def VerifyBuild(self, tech_plan: str,slug: str,history: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = self.__options.merge_options(baml_options).create_http_request_sync(function_name="VerifyBuild", args={
            "tech_plan": tech_plan,"slug": slug,"history": history,
        }, mode="request")
        return __result__
    

class BamlHttpStreamRequestClient:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def ArchitectFeature(self, feature_name: str,slug: str,vault_structure: str,vault_entrypoints: str,acceptance_criteria: str,decision_text: typing.Optional[str] = None,research_findings: typing.Optional[str] = None,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = self.__options.merge_options(baml_options).create_http_request_sync(function_name="ArchitectFeature", args={
            "feature_name": feature_name,"slug": slug,"vault_structure": vault_structure,"vault_entrypoints": vault_entrypoints,"acceptance_criteria": acceptance_criteria,"decision_text": decision_text,"research_findings": research_findings,
        }, mode="stream")
        return __result__
    def BuildFeature(self, tech_plan: str,decision_text: typing.Optional[str],slug: str,feature_description: str,history: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = self.__options.merge_options(baml_options).create_http_request_sync(function_name="BuildFeature", args={
            "tech_plan": tech_plan,"decision_text": decision_text,"slug": slug,"feature_description": feature_description,"history": history,
        }, mode="stream")
        return __result__
    def ClarifySpecs(self, specs_content: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = self.__options.merge_options(baml_options).create_http_request_sync(function_name="ClarifySpecs", args={
            "specs_content": specs_content,
        }, mode="stream")
        return __result__
    def MapAndIndex(self, git_diff: str,slug: str,feature_description: str,plan_text: str,tech_plan: str,index_text: str,history: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = self.__options.merge_options(baml_options).create_http_request_sync(function_name="MapAndIndex", args={
            "git_diff": git_diff,"slug": slug,"feature_description": feature_description,"plan_text": plan_text,"tech_plan": tech_plan,"index_text": index_text,"history": history,
        }, mode="stream")
        return __result__
    def PlanFeatures(self, specs_content: str,clarifications: str,existing_plan: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = self.__options.merge_options(baml_options).create_http_request_sync(function_name="PlanFeatures", args={
            "specs_content": specs_content,"clarifications": clarifications,"existing_plan": existing_plan,
        }, mode="stream")
        return __result__
    def PreflightMap(self, file_listing: str,manifest_files: str,history: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = self.__options.merge_options(baml_options).create_http_request_sync(function_name="PreflightMap", args={
            "file_listing": file_listing,"manifest_files": manifest_files,"history": history,
        }, mode="stream")
        return __result__
    def RefineApproaches(self, feature_name: str,slug: str,vault_overview: str,vault_structure: str,vault_deps: str,acceptance_criteria: str,research_findings: typing.Optional[str] = None,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = self.__options.merge_options(baml_options).create_http_request_sync(function_name="RefineApproaches", args={
            "feature_name": feature_name,"slug": slug,"vault_overview": vault_overview,"vault_structure": vault_structure,"vault_deps": vault_deps,"acceptance_criteria": acceptance_criteria,"research_findings": research_findings,
        }, mode="stream")
        return __result__
    def ResearchFeature(self, feature_name: str,slug: str,research_type: str,sub_prompt: typing.Optional[str],vault_overview: str,vault_structure: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = self.__options.merge_options(baml_options).create_http_request_sync(function_name="ResearchFeature", args={
            "feature_name": feature_name,"slug": slug,"research_type": research_type,"sub_prompt": sub_prompt,"vault_overview": vault_overview,"vault_structure": vault_structure,
        }, mode="stream")
        return __result__
    def VerifyBuild(self, tech_plan: str,slug: str,history: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = self.__options.merge_options(baml_options).create_http_request_sync(function_name="VerifyBuild", args={
            "tech_plan": tech_plan,"slug": slug,"history": history,
        }, mode="stream")
        return __result__
    

b = BamlSyncClient(DoNotUseDirectlyCallManager({}))