# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

from . import types
from . import stream_types


type_map = {

    "types.Approach": types.Approach,
    "stream_types.Approach": stream_types.Approach,

    "types.BuilderFinal": types.BuilderFinal,
    "stream_types.BuilderFinal": stream_types.BuilderFinal,

    "types.BuilderQuestionsEntry": types.BuilderQuestionsEntry,
    "stream_types.BuilderQuestionsEntry": stream_types.BuilderQuestionsEntry,

    "types.BuilderReport": types.BuilderReport,
    "stream_types.BuilderReport": stream_types.BuilderReport,

    "types.BuilderToolCall": types.BuilderToolCall,
    "stream_types.BuilderToolCall": stream_types.BuilderToolCall,

    "types.ClarifierOutput": types.ClarifierOutput,
    "stream_types.ClarifierOutput": stream_types.ClarifierOutput,

    "types.ClarifierQuestion": types.ClarifierQuestion,
    "stream_types.ClarifierQuestion": stream_types.ClarifierQuestion,

    "types.CriterionMap": types.CriterionMap,
    "stream_types.CriterionMap": stream_types.CriterionMap,

    "types.Decision": types.Decision,
    "stream_types.Decision": stream_types.Decision,

    "types.Failure": types.Failure,
    "stream_types.Failure": stream_types.Failure,

    "types.Feature": types.Feature,
    "stream_types.Feature": stream_types.Feature,

    "types.FeaturePlan": types.FeaturePlan,
    "stream_types.FeaturePlan": stream_types.FeaturePlan,

    "types.FileSpec": types.FileSpec,
    "stream_types.FileSpec": stream_types.FileSpec,

    "types.MapperFinal": types.MapperFinal,
    "stream_types.MapperFinal": stream_types.MapperFinal,

    "types.MapperReport": types.MapperReport,
    "stream_types.MapperReport": stream_types.MapperReport,

    "types.MapperToolCall": types.MapperToolCall,
    "stream_types.MapperToolCall": stream_types.MapperToolCall,

    "types.ResearchFinding": types.ResearchFinding,
    "stream_types.ResearchFinding": stream_types.ResearchFinding,

    "types.ResearchFindings": types.ResearchFindings,
    "stream_types.ResearchFindings": stream_types.ResearchFindings,

    "types.TechPlan": types.TechPlan,
    "stream_types.TechPlan": stream_types.TechPlan,

    "types.ToolCall": types.ToolCall,
    "stream_types.ToolCall": stream_types.ToolCall,

    "types.VerifierFinal": types.VerifierFinal,
    "stream_types.VerifierFinal": stream_types.VerifierFinal,

    "types.VerifierReport": types.VerifierReport,
    "stream_types.VerifierReport": stream_types.VerifierReport,

    "types.VerifierToolCall": types.VerifierToolCall,
    "stream_types.VerifierToolCall": stream_types.VerifierToolCall,


}