# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
from enum import Enum


from pydantic import BaseModel, ConfigDict, Field


import baml_py

CheckT = typing_extensions.TypeVar('CheckT')
CheckName = typing_extensions.TypeVar('CheckName', bound=str)

class Check(BaseModel):
    name: str
    expression: str
    status: str
class Checked(BaseModel, typing.Generic[CheckT, CheckName]):
    value: CheckT
    checks: typing.Dict[CheckName, Check]

def get_checks(checks: typing.Dict[CheckName, Check]) -> typing.List[Check]:
    return list(checks.values())

def all_succeeded(checks: typing.Dict[CheckName, Check]) -> bool:
    return all(check.status == "succeeded" for check in get_checks(checks))
# #########################################################################
# Generated enums (0)
# #########################################################################

# #########################################################################
# Generated classes (23)
# #########################################################################

class Approach(BaseModel):
    name: str = Field(description='2-4 word approach name')
    description: str = Field(description='3-5 sentence explanation')
    simplicity: int = Field(description='1-5')
    completeness: int = Field(description='1-5')
    risk: int = Field(description='1-5, 5=lowest risk')
    fit: int = Field(description='1-5')

class BuilderFinal(BaseModel):
    report: "BuilderReport"

class BuilderQuestionsEntry(BaseModel):
    slug: str
    timestamp: str = Field(description='ISO 8601')
    questions: typing.List[str] = Field(description='Markdown list items with - [ ] prefix')

class BuilderReport(BaseModel):
    commit_made: bool
    open_questions: typing.List[str] = Field(description='Ambiguities that surfaced during implementation')
    deviations: typing.List[str] = Field(description='What changed from the plan and why')

class BuilderToolCall(BaseModel):
    tool_name: str = Field(description='vault_read | vault_write | run_shell_command')
    args: typing.Dict[str, str]

class ClarifierOutput(BaseModel):
    has_ambiguities: bool
    questions: typing.List["ClarifierQuestion"] = Field(description='Up to 10 blocking questions')

class ClarifierQuestion(BaseModel):
    feature: str = Field(description='Feature or file the question targets')
    question: str = Field(description='Single-sentence question')
    context: str = Field(description='Why this matters — 1-2 sentences')

class CriterionMap(BaseModel):
    criterion_number: int
    verification: str = Field(description='Concrete test or verification step')

class Decision(BaseModel):
    approaches: typing.List["Approach"] = Field(description='Exactly 3 distinct approaches')
    chosen: int = Field(description='1, 2, or 3 — highest total score, prefer simpler on tie')
    rationale: str = Field(description='Why this approach was chosen')

class Failure(BaseModel):
    check_type: str = Field(description='typecheck | lint | test')
    command: str = Field(description='The command that was run')
    error_message: str = Field(description='Trimmed error output')
    likely_cause: str = Field(description='One-sentence diagnosis')
    criterion_impact: str = Field(description='Which criterion this affects, or \'No criterion mapped\'')

class Feature(BaseModel):
    slug: str = Field(description='kebab-case, alphanumerics and hyphens only, max 40 chars')
    description: str = Field(description='One-line feature summary')
    acceptance_criteria: typing.List[str] = Field(description='2-8 user-observable invariants')

class FeaturePlan(BaseModel):
    features: typing.List["Feature"]

class FileSpec(BaseModel):
    path: str
    purpose: str

class MapperFinal(BaseModel):
    report: "MapperReport"

class MapperReport(BaseModel):
    entities_updated: typing.List[str]
    log_entry: str = Field(description='One-sentence summary for log.md')
    deviations_summary: str = Field(description='Deviations section text for TECH.md, or \'Implementation matched plan — no deviations.\'')

class MapperToolCall(BaseModel):
    tool_name: str = Field(description='vault_read | vault_write | run_shell_command')
    args: typing.Dict[str, str]

class ResearchFinding(BaseModel):
    title: str
    insight: str = Field(description='2-4 sentence key insight')
    relevance: str = Field(description='One-sentence relevance to this feature')
    confidence: str = Field(description='High | Medium | Low')
    source_url: typing.Optional[str] = Field(default=None, description='If web search was used')

class ResearchFindings(BaseModel):
    findings: typing.List["ResearchFinding"]
    recommendations: typing.List[str]

class TechPlan(BaseModel):
    context: str = Field(description='What\'s being built and current system context')
    files_to_create: typing.List["FileSpec"]
    files_to_modify: typing.List["FileSpec"]
    interfaces: str = Field(description='Function signatures / API shapes / type definitions')
    edge_cases: typing.List[str]
    criteria_mapping: typing.List["CriterionMap"]

class ToolCall(BaseModel):
    tool_name: str = Field(description='vault_read | vault_write | run_shell_command | web_search')
    args: typing.Dict[str, str]

class VerifierFinal(BaseModel):
    report: "VerifierReport"

class VerifierReport(BaseModel):
    status: str = Field(description='PASSED or FAILED')
    failures: typing.List["Failure"]
    fix_hints: typing.List[str] = Field(description='Concrete file-level suggestions')

class VerifierToolCall(BaseModel):
    tool_name: str = Field(description='vault_read | run_shell_command')
    args: typing.Dict[str, str]

# #########################################################################
# Generated type aliases (3)
# #########################################################################


BuilderStep: typing_extensions.TypeAlias = typing.Union["BuilderToolCall", "BuilderFinal"]


MapperStep: typing_extensions.TypeAlias = typing.Union["MapperToolCall", "MapperFinal"]


VerifierStep: typing_extensions.TypeAlias = typing.Union["VerifierToolCall", "VerifierFinal"]
